---
# Development environment override
services:
  php:
    build:
      context: .
      target: dev
    volumes:
      - ./:/app
      - ./var/log/dev.log:/app/var/log/dev.log
      - ./frankenphp/Caddyfile:/etc/frankenphp/Caddyfile:ro
      - ./frankenphp/conf.d/20-app.dev.ini:/usr/local/etc/php/app.conf.d/20-app.dev.ini:ro
    environment:
      FRANKENPHP_WORKER_CONFIG: watch
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
      APP_ENV: "${APP_ENV:-dev}"
    extra_hosts:
      - host.docker.internal:host-gateway
    tty: true
    ports:
      - name: http
        target: 80
        published: 8080
        protocol: tcp
      - name: https
        target: 443
        published: 8443
        protocol: tcp
      - name: http3
        target: 443
        published: 8443
        protocol: udp

  messenger:
    volumes:
      - ./:/app

  scheduler:
    volumes:
      - ./:/app

###> doctrine/doctrine-bundle ###
  database:
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

###> redis ###
  redis:
    ports:
      - '6379:6379'
###< redis ###
