<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251221130750 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE deployment_queue_repository (deployment_queue_id BIGINT NOT NULL, repository_id INT NOT NULL, PRIMARY KEY (deployment_queue_id, repository_id))');
        $this->addSql('CREATE INDEX IDX_96E1A3AF78199EC5 ON deployment_queue_repository (deployment_queue_id)');
        $this->addSql('CREATE INDEX IDX_96E1A3AF50C9D4F7 ON deployment_queue_repository (repository_id)');
        $this->addSql('CREATE TABLE deployment_notify_user (deployment_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (deployment_id, user_id))');
        $this->addSql('CREATE INDEX IDX_A84E097E9DF4CE98 ON deployment_notify_user (deployment_id)');
        $this->addSql('CREATE INDEX IDX_A84E097EA76ED395 ON deployment_notify_user (user_id)');
        $this->addSql('CREATE TABLE repository_blocked_by_deployment (blocker_id INT NOT NULL, repository_id INT NOT NULL, PRIMARY KEY (blocker_id, repository_id))');
        $this->addSql('CREATE INDEX IDX_E3700CCB548D5975 ON repository_blocked_by_deployment (blocker_id)');
        $this->addSql('CREATE INDEX IDX_E3700CCB50C9D4F7 ON repository_blocked_by_deployment (repository_id)');
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, slack_id VARCHAR(255) NOT NULL, administrator_id BIGINT DEFAULT NULL, workspace_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D6494B09E92C ON "user" (administrator_id)');
        $this->addSql('CREATE INDEX IDX_8D93D64982D40A1F ON "user" (workspace_id)');
        $this->addSql('ALTER TABLE deployment_queue_repository ADD CONSTRAINT FK_96E1A3AF78199EC5 FOREIGN KEY (deployment_queue_id) REFERENCES queue (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deployment_queue_repository ADD CONSTRAINT FK_96E1A3AF50C9D4F7 FOREIGN KEY (repository_id) REFERENCES repository (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deployment_notify_user ADD CONSTRAINT FK_A84E097E9DF4CE98 FOREIGN KEY (deployment_id) REFERENCES queued_user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE deployment_notify_user ADD CONSTRAINT FK_A84E097EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE repository_blocked_by_deployment ADD CONSTRAINT FK_E3700CCB548D5975 FOREIGN KEY (blocker_id) REFERENCES repository (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE repository_blocked_by_deployment ADD CONSTRAINT FK_E3700CCB50C9D4F7 FOREIGN KEY (repository_id) REFERENCES repository (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6494B09E92C FOREIGN KEY (administrator_id) REFERENCES administrator (id)');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D64982D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id)');
        $this->addSql('ALTER TABLE queue ADD type VARCHAR(255) DEFAULT \'basic\' NOT NULL');
        $this->addSql('ALTER TABLE queued_user ADD type VARCHAR(255) DEFAULT \'basic\' NOT NULL');
        $this->addSql('ALTER TABLE queued_user ADD link VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE queued_user ADD description TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE queued_user ADD repository_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE queued_user DROP user_id');
        $this->addSql('ALTER TABLE queued_user ADD user_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE queued_user ADD CONSTRAINT FK_EA70565DA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id)');
        $this->addSql('ALTER TABLE queued_user ADD CONSTRAINT FK_EA70565D50C9D4F7 FOREIGN KEY (repository_id) REFERENCES repository (id)');
        $this->addSql('CREATE INDEX IDX_EA70565DA76ED395 ON queued_user (user_id)');
        $this->addSql('CREATE INDEX IDX_EA70565D50C9D4F7 ON queued_user (repository_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE deployment_queue_repository DROP CONSTRAINT FK_96E1A3AF78199EC5');
        $this->addSql('ALTER TABLE deployment_queue_repository DROP CONSTRAINT FK_96E1A3AF50C9D4F7');
        $this->addSql('ALTER TABLE deployment_notify_user DROP CONSTRAINT FK_A84E097E9DF4CE98');
        $this->addSql('ALTER TABLE deployment_notify_user DROP CONSTRAINT FK_A84E097EA76ED395');
        $this->addSql('ALTER TABLE repository_blocked_by_deployment DROP CONSTRAINT FK_E3700CCB548D5975');
        $this->addSql('ALTER TABLE repository_blocked_by_deployment DROP CONSTRAINT FK_E3700CCB50C9D4F7');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6494B09E92C');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D64982D40A1F');
        $this->addSql('DROP TABLE deployment_queue_repository');
        $this->addSql('DROP TABLE deployment_notify_user');
        $this->addSql('DROP TABLE repository_blocked_by_deployment');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('ALTER TABLE queue DROP type');
        $this->addSql('ALTER TABLE queued_user DROP CONSTRAINT FK_EA70565DA76ED395');
        $this->addSql('ALTER TABLE queued_user DROP CONSTRAINT FK_EA70565D50C9D4F7');
        $this->addSql('DROP INDEX IDX_EA70565DA76ED395');
        $this->addSql('DROP INDEX IDX_EA70565D50C9D4F7');
        $this->addSql('ALTER TABLE queued_user DROP type');
        $this->addSql('ALTER TABLE queued_user DROP link');
        $this->addSql('ALTER TABLE queued_user DROP description');
        $this->addSql('ALTER TABLE queued_user DROP repository_id');
        $this->addSql('ALTER TABLE queued_user DROP user_id');
        $this->addSql('ALTER TABLE queued_user ADD user_id INT NOT NULL');
    }
}
