<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251212112528 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE administrator (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, added_by_id BIGINT DEFAULT NULL, workspace_id BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_58DF065155B127A4 ON administrator (added_by_id)');
        $this->addSql('CREATE INDEX IDX_58DF065182D40A1F ON administrator (workspace_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_58DF0651A76ED39582D40A1F ON administrator (user_id, workspace_id)');
        $this->addSql('CREATE TABLE queue (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, expiry_minutes INT DEFAULT NULL, maximum_entries_per_user INT DEFAULT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, workspace_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7FFD7F6382D40A1F ON queue (workspace_id)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_7FFD7F635E237E0682D40A1F ON queue (name, workspace_id)');
        $this->addSql('CREATE TABLE queued_user (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id VARCHAR(255) NOT NULL, expires_at TIMESTAMP(6) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, queue_id BIGINT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA70565D477B5BAE ON queued_user (queue_id)');
        $this->addSql('CREATE TABLE workspace (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, slack_id VARCHAR(255) NOT NULL, bot_token VARCHAR(255) NOT NULL, created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D94001963F6D2C9 ON workspace (slack_id)');
        $this->addSql('ALTER TABLE administrator ADD CONSTRAINT FK_58DF065155B127A4 FOREIGN KEY (added_by_id) REFERENCES administrator (id)');
        $this->addSql('ALTER TABLE administrator ADD CONSTRAINT FK_58DF065182D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE queue ADD CONSTRAINT FK_7FFD7F6382D40A1F FOREIGN KEY (workspace_id) REFERENCES workspace (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE queued_user ADD CONSTRAINT FK_EA70565D477B5BAE FOREIGN KEY (queue_id) REFERENCES queue (id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE administrator DROP CONSTRAINT FK_58DF065155B127A4');
        $this->addSql('ALTER TABLE administrator DROP CONSTRAINT FK_58DF065182D40A1F');
        $this->addSql('ALTER TABLE queue DROP CONSTRAINT FK_7FFD7F6382D40A1F');
        $this->addSql('ALTER TABLE queued_user DROP CONSTRAINT FK_EA70565D477B5BAE');
        $this->addSql('DROP TABLE administrator');
        $this->addSql('DROP TABLE queue');
        $this->addSql('DROP TABLE queued_user');
        $this->addSql('DROP TABLE workspace');
    }
}
